name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Mutiline Command
        run: |
          node -v
          npm -v
          hostnamectl
          df -h
  parallel_job:
    runs-on: macos-latest
    steps:
       - name: View SW version
         run: sw_vers
  depend_job:
    runs-on: windows-latest
    needs: [run-shell-commands]
    steps:
       - name: Show Hostname
         run: hostname 
    